### ISSUE TITLE
Service Provider not being init'd with commands

### ISSUE THREAD

**Issue by NoelDavies** [creolab/laravel-modules#100]
When using a command, the module's service provider isn't being booted whilst init'ing a module's commands, meaning seeding via repositories is impossible unless you rebind the repositories within the seeder.

**Comment by NoelDavies** [comment]
@bstrahija no explanation? :/ I assume it's due to this not being maintained?

**Comment by bstrahija** [comment]
Yeah, I'm not maintaining the package anymore since I don't think it makes sense for L5.

If you're up for a PR, feel free to send one.

**Comment by NoelDavies** [comment]
Fair enough man, kinda commented before I read the repo again. It's all good, I'm currently working with Symfony primarily at the moment. Thanks for the work on this repo though :) it helped out a fair bit.
