### ISSUE TITLE
Is there any update for Laravel 5 ?

### ISSUE THREAD

**Issue by fredrickm** [creolab/laravel-modules#107]
Creolab is not supporting to the latest version of Laravel.

**Comment by bstrahija** [comment]
I started working on the new version, but can't give an estimate when it's gonna be ready.

**Comment by naysumyat** [comment]
+1

**Comment by fredrickm** [comment]
Thank you. Now, We are waiting for the good news. If you need any help, We will assist you in this. 

Thanks again.

**Comment by jumilla** [comment]
Hi, all.

We have developed a module system 'Addon' that can be used with the latest Laravel version in 'Laravel Extension'.

Laravel Extension Pack
https://github.com/jumilla/laravel-extension

Try using all means!

**Comment by y80x86ol** [comment]
Oh,I need for laravel5
