### ISSUE TITLE
Add assets in a module

### ISSUE THREAD

**Issue by skalero01** [creolab/laravel-modules#109]
In the provided example here: https://github.com/bstrahija/laravel-modules-example/tree/master/app/modules/content

I can see that exists a folder called assets/css with one CSS, but i found that you don't call the CSS in any file, How should i call the css in this case to add it in the layout? Is there a way?

Regards

**Comment by baylonedward** [comment]
you first publish it.
php artisan modules:publish [name of the module]

then use it in the layout like how you use a regular css in laravel.

**Comment by skalero01** [comment]
I tried, but i found that in the layout in need to add something like this:

{{ HTML::style('packages/module/app_modules_integration/theme/assets/css/style.css') }}

Is there a function or something like that where i could call my css in my actual module? to call it in something like this?

{{ HTML::style('css/style.css') }}

Regards

**Comment by bstrahija** [comment]
The package is no longer maintained. For any requests please send PRs.
