### ISSUE TITLE
how to run project

### ISSUE THREAD

**Issue by MahdiPishguy** [creolab/laravel-modules#110]
hi all. how to run project?
after download and composer install and create database, run migrate i get this error:

Illuminate \ Database \ QueryException

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'modules.entries' doesn't exist (SQL: select \* from `entries`)

**Comment by chriskonnertz** [comment]
Note: This package does not support Laravel 5. Maybe that's the problem?

**Comment by bstrahija** [comment]
The package is no longer maintained. For any requests please send PRs.
