### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by devloe** [creolab/laravel-modules#111]
Hi, I get the following error when running composer:

Problem 1
    - illuminate/support v5.2.7 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement
....
....
....

As far as I can see, the problem is in the version of Laravel.

I'm using Laravel 4.2, and my require looks like:

"creolab/laravel-modules": "0.5.0"

Any toughts?

**Comment by bstrahija** [comment]
The package is no longer maintained. For any requests please send PRs.
