### ISSUE TITLE
5.0

### ISSUE THREAD

**Issue by xLink** [creolab/laravel-modules#85]
@bstrahija as you have no doubt seen the 5.0 release of laravel has a significant upgrade in the way the directories are structured etc.

I am currently wondering what plans you have for supporting 5.0, if atall.

**Comment by chriskonnertz** [comment]
So, L5 is (almost) complete. Any updates?

**Comment by samwilson** [comment]
+1 for L5 support.

**Comment by sangle137** [comment]
+1 for L5 support, thank you
